import Head from "next/head";

import Nav from "../components/Navbar";
import { SocialIcons } from "../components/SocialIcons";
import { Footer } from "../components/Footer";
import { Email } from "../components/Email";
import { About } from "../components/About";
import { AboutMe } from "../components/AboutMe";
import { WorkExperience } from "../components/WorkExperience";
import { Projects } from "../components/Projects";
import { Contact } from "../components/Contact";
import Script from "next/script";

export default function Home() {
  return (
    <>
      <Head>
        <title>Renuka Bhagyasri | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>
      <div className="">
        <Script src="https://third-party-script.js"></Script>

        <Nav />

        <About />
        <AboutMe />
        <WorkExperience />
        <Projects />

        <Contact />
        <SocialIcons />
        <Email />
        <Footer />

        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
          AOS.init();
          {/* AOS.refresh(); */}
        </script>
      </div>
      {/* </div> */}
    </>
  );
}
